{{- if eq (include "k8s-view.shouldCreateSecret" .) "true" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s-view.credentialsSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "k8s-view.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if and .Values.auth.basicAuth.enabled (not .Values.auth.basicAuth.existingSecret) }}
  basicAuthUser: {{ .Values.auth.basicAuth.user | b64enc | quote }}
  basicAuthPassword: {{ .Values.auth.basicAuth.password | b64enc | quote }}
  {{- end }}
  {{- if and .Values.auth.oidc.enabled (not .Values.auth.oidc.existingSecret) .Values.auth.oidc.clientSecret }}
  oidcClientSecret: {{ .Values.auth.oidc.clientSecret | b64enc | quote }}
  {{- end }}
  {{- if and .Values.auth.ldap.enabled (not .Values.auth.ldap.existingSecret) .Values.auth.ldap.bindPassword }}
  ldapBindPassword: {{ .Values.auth.ldap.bindPassword | b64enc | quote }}
  {{- end }}
{{- end }}
